---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.md"
exclude_paths:
- test/
- "**/.rubocop.yml"
